-- ****************************************************************************
-- *
-- *  PROJECT:     vRoleplay
-- *  FILE:        server/classes/Gameplay/DrugFactories/FactoryWar.lua
-- *  PURPOSE:     Factory War class
-- *
-- ****************************************************************************
