CHESS_CONSTANT = {
 PATH = "files/images/Chess/",
 CHESS_URL =
{
	"King",
	"Queen",
	"Rook",
	"Bishop",
	"Knight",
	"Pawn",
},

 TILE_COLORS =
{
	tocolor(150,150,150,255),
	tocolor(72, 60, 50,255),
},
 PIECE_COLORS =
{
	tocolor(255,255,255,255),
	tocolor(0,0,0,255),

},
 MARK_COLOR = tocolor(0,200,200,50),
 ERROR_MARK_COLOR = tocolor(200,0,0,0),
 NEXT_STEP_COLOR = tocolor(0,200,0,50),
 }

CHESS_CONSTANT.WIDTH = screenWidth*0.4
CHESS_CONSTANT.TILE_SIZE = CHESS_CONSTANT.WIDTH/8
CHESS_CONSTANT.HEIGHT = CHESS_CONSTANT.WIDTH
CHESS_CONSTANT.START_X = screenWidth*0.5 -CHESS_CONSTANT.WIDTH*0.5
CHESS_CONSTANT.START_Y = screenHeight*0.55 - CHESS_CONSTANT.HEIGHT*0.5
CHESS_CONSTANT.MARGIN = CHESS_CONSTANT.TILE_SIZE/4
CHESS_CONSTANT.MARGIN_COLOR = tocolor(102,51,0)
CHESS_CONSTANT.URL_TILE = "tile"
CHESS_CONSTANT.CLOCK_BG_COLOR = tocolor(52, 52, 52)
CHESS_CONSTANT.CLOCK_HEIGHT = CHESS_CONSTANT.HEIGHT*0.12
CHESS_CONSTANT.CLOCK_WIDTH = CHESS_CONSTANT.WIDTH*0.5
CHESS_CONSTANT.CLOCK_X = (CHESS_CONSTANT.START_X+CHESS_CONSTANT.WIDTH/2)-CHESS_CONSTANT.CLOCK_WIDTH/2
CHESS_CONSTANT.CLOCK_Y = CHESS_CONSTANT.START_Y-CHESS_CONSTANT.CLOCK_HEIGHT*1.1- CHESS_CONSTANT.MARGIN*2
CHESS_CONSTANT.FONT_PATH = "files/fonts/"
CHESS_CONSTANT.FONT_INFO = "clear"
if screenWidth >= 1600 and screenHeight >= 720 then
	CHESS_CONSTANT.FONT_CHAPAZA = dxCreateFont(CHESS_CONSTANT.FONT_PATH.."Chapaza.ttf",24)
	CHESS_CONSTANT.FONT_INFO_SCALE = 2
else
	CHESS_CONSTANT.FONT_CHAPAZA = dxCreateFont(CHESS_CONSTANT.FONT_PATH.."Chapaza.ttf",16)
	CHESS_CONSTANT.FONT_INFO_SCALE = 1
end
CHESS_CONSTANT.FONT_CHAPAZA_HEIGHT = dxGetFontHeight(1,CHESS_CONSTANT.FONT_CHAPAZA)

CHESS_CONSTANT.AUDIO_PATH = "files/audio/chess/"
