
PERMISSIONS_INFO = { -- name = {{type, id} type = 0 for all, {faction min rank, company min rank, group min rank}}
	["invite"] =				{{0}, {["faction"] = 4, ["company"] = 3, ["group"] = 0}},
	["uninvite"] =				{{0}, {["faction"] = 4, ["company"] = 3, ["group"] = 3}},
	["changeRank"] =			{{0}, {["faction"] = 4, ["company"] = 3, ["group"] = 1}},
	["toggleLoan"] =			{{0}, {["faction"] = 4, ["company"] = 3, ["group"] = 1}},
	["editLoan"] =				{{0}, {["faction"] = 4, ["company"] = 3, ["group"] = 1}},
	["toggleWeapon"] =			{{0}, {["faction"] = 4, ["company"] = nil, ["group"] = nil}},
	["withdrawMoney"] =			{{0}, {["faction"] = 5, ["company"] = 4, ["group"] = 0}},
	["vehicleRespawnAll"] =		{{0}, {["faction"] = 0, ["company"] = 0, ["group"] = 0}},
	["editRankSkins"] =			{{0}, {["faction"] = 4, ["company"] = 3, ["group"] = nil}},
	["editWeaponPermissions"] =	{{0}, {["faction"] = 4, ["company"] = nil, ["group"] = nil}},
	["editDiplomacy"] =			{{1, {FactionStaticId.LCN, FactionStaticId.YAKUZA, FactionStaticId.GROVE, FactionStaticId.BALLAS, FactionStaticId.OUTLAWS, FactionStaticId.VATOS, FactionStaticId.TRIAD, FactionStaticId.BRIGADA}}, {["faction"] = 0, ["company"] = nil, ["group"] = nil}}, -- f done
	-----["startGangWar"] =			{{1, {FactionStaticId.LCN, FactionStaticId.YAKUZA, FactionStaticId.GROVE, FactionStaticId.BALLAS, FactionStaticId.OUTLAWS, FactionStaticId.VATOS, FactionStaticId.TRIAD, FactionStaticId.BRIGADA}}, {["faction"] = 0, ["company"] = nil, ["group"] = nil}}, -- f done
	-----["joinGangWar"] =			{{1, {FactionStaticId.LCN, FactionStaticId.YAKUZA, FactionStaticId.GROVE, FactionStaticId.BALLAS, FactionStaticId.OUTLAWS, FactionStaticId.VATOS, FactionStaticId.TRIAD, FactionStaticId.BRIGADA}}, {["faction"] = 0, ["company"] = nil, ["group"] = nil}}, -- f done
	["editBinds"] =				{{0}, {["faction"] = 4, ["company"] = 3, ["group"] = nil}},
	["editEquipment"] =			{{0}, {["faction"] = 4, ["company"] = nil, ["group"] = nil}},
	["editActionPermissions"] =	{{0}, {["faction"] = 4, ["company"] = nil, ["group"] = 0}},
	["addVehicle"] =			{{0}, {["faction"] = nil, ["company"] = nil, ["group"] = 0}},
	["removeVehicle"] =			{{0}, {["faction"] = nil, ["company"] = nil, ["group"] = 0}},
	["editVehicleTuning"] =		{{0}, {["faction"] = nil, ["company"] = nil, ["group"] = 0}},
	["editVehicleTexture"] =	{{0}, {["faction"] = nil, ["company"] = nil, ["group"] = 0}},
	["buyRcVehicles"] =			{{0}, {["faction"] = nil, ["company"] = nil, ["group"] = 0}},
	["setVehicleForSale"] =		{{0}, {["faction"] = nil, ["company"] = nil, ["group"] = 0}},
	["stopVehicleForSale"] =	{{0}, {["faction"] = nil, ["company"] = nil, ["group"] = 0}},
	["setVehicleForRent"] =		{{0}, {["faction"] = nil, ["company"] = nil, ["group"] = 0}},
	["stopVehicleForRent"] =	{{0}, {["faction"] = nil, ["company"] = nil, ["group"] = 0}},
	["buyBIZ"] =				{{0}, {["faction"] = nil, ["company"] = nil, ["group"] = 0}},
	["sellBIZ"] =				{{0}, {["faction"] = nil, ["company"] = nil, ["group"] = 0}},
	["withdrawBIZMoney"] =		{{0}, {["faction"] = nil, ["company"] = nil, ["group"] = 0}},
	["vehiclePark"] =			{{0}, {["faction"] = nil, ["company"] = nil, ["group"] = 0}},
	["deleteGroup"] =			{{0}, {["faction"] = nil, ["company"] = nil, ["group"] = 6}},
	["vehicleRespawn"] =		{{0}, {["faction"] = nil, ["company"] = nil, ["group"] = 0}},
	["renameGroup"] =			{{0}, {["faction"] = nil, ["company"] = nil, ["group"] = 5}},
	["changeGroupType"] =		{{0}, {["faction"] = nil, ["company"] = nil, ["group"] = 4}},
	["changeRankNames"] =		{{0}, {["faction"] = nil, ["company"] = nil, ["group"] = 0}},
	["buyProperty"] =			{{0}, {["faction"] = nil, ["company"] = nil, ["group"] = 0}},
	["sellProperty"] =			{{0}, {["faction"] = nil, ["company"] = nil, ["group"] = 0}},
	["manageImmoDepot"] =		{{0}, {["faction"] = nil, ["company"] = nil, ["group"] = 0}},
	["startBusTour"] =			{{2, {CompanyStaticId.EPT}}, {["faction"] = nil, ["company"] = 0, ["group"] = nil}},
	["startVehicleImport"] =	{{2, {CompanyStaticId.EPT}}, {["faction"] = nil, ["company"] = 0, ["group"] = nil}},
	["startStreetRace"] =		{{2, {CompanyStaticId.SANNEWS}}, {["faction"] = nil, ["company"] = 0, ["group"] = nil}},
	["addBlip"] =				{{2, {CompanyStaticId.SANNEWS}}, {["faction"] = nil, ["company"] = 0, ["group"] = nil}}, -- also includes remove
	["useSpeedCam"]	=			{{1, {FactionStaticId.SAPD}}, {["faction"] = 0, ["company"] = nil, ["group"] = nil}},
	["useRhino"]	=			{{1, {FactionStaticId.MBT}}, {["faction"] = 1, ["company"] = nil, ["group"] = nil}},
	["useHydra"]	=			{{1, {FactionStaticId.MBT}}, {["faction"] = 1, ["company"] = nil, ["group"] = nil}},
	["useHunter"]	=			{{1, {FactionStaticId.MBT}}, {["faction"] = 1, ["company"] = nil, ["group"] = nil}},
	["toggleAreaAlarm"]	=		{{1, {FactionStaticId.MBT}}, {["faction"] = 1, ["company"] = nil, ["group"] = nil}},
	["setPaNote"]	=			{{1, {FactionStaticId.MBT}}, {["faction"] = 5, ["company"] = nil, ["group"] = nil}},
	["releaseFromJail"]	=		{{1, {FactionStaticId.SAPD, FactionStaticId.FBI, FactionStaticId.MBT}}, {["faction"] = 1, ["company"] = nil, ["group"] = nil}},
	["clearBugLog"]	=			{{1, {FactionStaticId.FBI}}, {["faction"] = 0, ["company"] = nil, ["group"] = nil}},
	["disableBug"]	=			{{1, {FactionStaticId.FBI}}, {["faction"] = 0, ["company"] = nil, ["group"] = nil}},
	["changePermissions"] =		{{0}, {["faction"] = 5, ["company"] = 4, ["group"] = 5}},
}

PERMISSION_NAMES = {
	["invite"] =				"Spieler einladen",
	["uninvite"] =				"Spieler rauswerfen",
	["changeRank"] =			"Spielerrang ändern",
	["toggleLoan"] =			"Gehalt de/aktivieren",
	["editLoan"] =				"Gehalt verwalten",
	["toggleWeapon"] =			"Waffenentnahme de/aktivieren",
	["withdrawMoney"] =			"Kassenauszahlung",
	["vehicleRespawnAll"] =		"Alle Fahrzeuge respawnen",
	["editRankSkins"] =			"Rangkleidung verwalten",
	["editWeaponPermissions"] =	"Waffenberechtigung verwalten",
	["editDiplomacy"] =			"Diplomatie verwalten",
	-----["startGangWar"] =			"Gangwar starten",
	-----["joinGangWar"] =			"Am Gangwar teilnehmen",
	["editBinds"] =				"Binds verwalten",
	["editEquipment"] =			"Equipmentrechte verwalten",
	["editActionPermissions"] =	"Aktionsrechte verwalten",
	["addVehicle"] =			"Fahrzeuge hinzufügen",
	["removeVehicle"] =			"Fahrzeuge entfernen",
	["editVehicleTuning"] =		"Fahrzeuge tunen",
	["editVehicleTexture"] =	"Speziallackierung ändern",
	["buyRcVehicles"] =			"RC Fahrzeuge kaufen",
	["setVehicleForSale"] =		"Fahrzeuge zum Verkauf stellen",
	["stopVehicleForSale"] =	"Fahrzeugverkauf beenden",
	["setVehicleForRent"] =		"Fahrzeuge zur Vermietung stellen",
	["stopVehicleForRent"] =	"Fahrzeugvermietung beenden",
	["buyBIZ"] =				"Geschäfte kaufen",
	["sellBIZ"] =				"Geschäfte verkaufen",
	["withdrawBIZMoney"] =		"Kasse von Geschäften leeren",
	["vehiclePark"] =			"Fahreuge parken",
	["deleteGroup"] =			"Gruppe löschen",
	["vehicleRespawn"] =		"Fahrzeuge respawnen",
	["renameGroup"] =			"Gruppe umbenennen",
	["changeGroupType"] =		"Gruppentyp ändern",
	["changeRankNames"] =		"Rangnamen verwalten",
	["buyProperty"] =			"Immobilien kaufen",
	["sellProperty"] =			"Immobilien verkaufen",
	["startBusTour"] =			"Buslinie starten",
	["startVehicleImport"] =	"Fahrzeugimport starten",
	["startStreetRace"] =		"Straßenrennen starten",
	["addBlip"] =				"Blips hinzufügen/entfernen",
	["useSpeedCam"] =			"Blitzer aufstellen",
	["useRhino"] =				"Rhino benutzen",
	["useHydra"] =				"Hydra benutzen",
	["useHunter"] =				"Hunter benutzen",
	["toggleAreaAlarm"] =		"Area Alarm de/aktivieren",
	["setPaNote"] =				"GWD Note setzen",
	["releaseFromJail"] =		"Spieler ausknasten",
	["clearBugLog"] =			"Wanzenlog leeren",
	["disableBug"] =			"Wanze deaktivieren",
	["manageImmoDepot"] =		"Immobilien Depot verwalten",
	["changePermissions"] =		"Rechte verwalten (Beinhaltet Vollzugriff)",
}

ACTION_PERMISSIONS_INFO = {
	["WeaponTruck"] =			{{1, {FactionStaticId.LCN, FactionStaticId.YAKUZA, FactionStaticId.GROVE, FactionStaticId.BALLAS, FactionStaticId.OUTLAWS, FactionStaticId.VATOS, FactionStaticId.TRIAD, FactionStaticId.BRIGADA}}, {["faction"] = 0, ["company"] = nil, ["group"] = nil}}, 
	["WeaponTruckState"] =		{{1, {FactionStaticId.SAPD, FactionStaticId.FBI, FactionStaticId.MBT}}, {["faction"] = 0, ["company"] = nil, ["group"] = nil}}, 
	["StateEvidenceTruck"] =	{{1, {FactionStaticId.SAPD, FactionStaticId.FBI, FactionStaticId.MBT}}, {["faction"] = 0, ["company"] = nil, ["group"] = nil}}, 
	["PrisonBreak"] =			{{1, {FactionStaticId.LCN, FactionStaticId.YAKUZA, FactionStaticId.GROVE, FactionStaticId.BALLAS, FactionStaticId.OUTLAWS, FactionStaticId.VATOS, FactionStaticId.TRIAD, FactionStaticId.BRIGADA}}, {["faction"] = 0, ["company"] = nil, ["group"] = nil}}, 
	["WeedTruck"] =				{{1, {FactionStaticId.LCN, FactionStaticId.YAKUZA, FactionStaticId.GROVE, FactionStaticId.BALLAS, FactionStaticId.OUTLAWS, FactionStaticId.VATOS, FactionStaticId.TRIAD, FactionStaticId.BRIGADA}}, {["faction"] = 0, ["company"] = nil, ["group"] = nil}}, 
	["BankRobbery"] =			{{1, {FactionStaticId.LCN, FactionStaticId.YAKUZA, FactionStaticId.GROVE, FactionStaticId.BALLAS, FactionStaticId.OUTLAWS, FactionStaticId.VATOS, FactionStaticId.TRIAD, FactionStaticId.BRIGADA}}, {["faction"] = 0, ["company"] = nil, ["group"] = nil}}, 
	["JewelryStoreRobbery"] =	{{1, {FactionStaticId.LCN, FactionStaticId.YAKUZA, FactionStaticId.GROVE, FactionStaticId.BALLAS, FactionStaticId.OUTLAWS, FactionStaticId.VATOS, FactionStaticId.TRIAD, FactionStaticId.BRIGADA}}, {["faction"] = 0, ["company"] = nil, ["group"] = nil}}, 
	["ExplosiveTruck"] =		{{1, {FactionStaticId.LCN, FactionStaticId.YAKUZA, FactionStaticId.GROVE, FactionStaticId.BALLAS, FactionStaticId.OUTLAWS, FactionStaticId.VATOS, FactionStaticId.TRIAD, FactionStaticId.BRIGADA}}, {["faction"] = 0, ["company"] = nil, ["group"] = nil}}, 
	["Airdrop"] =				{{1, {FactionStaticId.LCN, FactionStaticId.YAKUZA, FactionStaticId.GROVE, FactionStaticId.BALLAS, FactionStaticId.OUTLAWS, FactionStaticId.VATOS, FactionStaticId.TRIAD, FactionStaticId.BRIGADA}}, {["faction"] = 0, ["company"] = nil, ["group"] = nil}}, 

	--[[["ShopRob"] =				{{3}, {["faction"] = nil, ["company"] = nil, ["group"] = 0}}, 
	["HouseRob"] =				{{3}, {["faction"] = nil, ["company"] = nil, ["group"] = 0}}, 
	["ShopVehicleRob"] =		{{3}, {["faction"] = nil, ["company"] = nil, ["group"] = 0}},]]
}

ACTION_PERMISSION_NAMES = {
	["WeaponTruck"] =			"Waffentruck", 
	["WeaponTruckState"] =		"Staatswaffentruck", 
	["StateEvidenceTruck"] =	"Geldtruck", 
	["PrisonBreak"] =			"Knastausbruch", 
	["WeedTruck"] =				"Drogentruck", 
	["BankRobbery"] =			"Banküberfall",
	["JewelryStoreRobbery"] =	"Juwelierraub",
	["ExplosiveTruck"] =		"Sprengstoff beschaffen",
	["Airdrop"] =				"Airdrop", 

	--[[["ShopRob"] =				"Shopüberfall", 
	["HouseRob"] =				"Hausraub",
	["ShopVehicleRob"] =		"Shopfahrzeug Diebstahl",]]
}