-- ****************************************************************************
-- *
-- *  PROJECT:     vRoleplay
-- *  FILE:        server/classes/VehicleTuning.lua
-- *  PURPOSE:     Vehicle tuning garage class
-- *
-- ****************************************************************************
